### ISSUE TITLE
Change Monitored status

### ISSUE THREAD

**Issue by theCheek** [onedr0p/sonarr-api#1]
Hi There,

I've been looking for a way to interface with Sonarr from within some bash scripts, and stumbled upon your github, which looks very promising.
Can you recommend the most efficient way of using your code to tell sonarr to monitor all episodes of a specific season of a specific series? I'm assuming this will be a PUT request for episode/{id} of Sonarr's API, but your readme doesn't seem to have any PUT examples.
Thanks

**Comment by onedr0p** [comment]
PUT will look like a POST request, I believe it should work. You can use sonarr.put() instead of sonarr.post()
